import os

def populate():

    add_station(name="West Ruislip", html="West Ruislip", variableName="West_Ruislip")
    add_station(name="Ruislip Gardens", html="Ruislip<br/>Gardens", variableName="Ruislip_Gardens")
    add_station(name="South Ruislip", html="South Ruislip", variableName="South_Ruislip")
    add_station(name="Northolt", html="Northolt", variableName="Northolt")
    add_station(name="Greenford", html="Greenford", variableName="Greenford")
    add_station(name="Perivale", html="Perivale", variableName="Perivale")
    add_station(name="Hanger Lane", html="Hanger Lane", variableName="Hanger_Lane")
    add_station(name="Ealing Broadway", html="Ealing Broadway", variableName="Ealing_Broadway")
    add_station(name="West Acton", html="West<br/>Acton", variableName="West_Acton")
    add_station(name="North Acton", html="North<br/>Acton", variableName="North_Acton")
    add_station(name="East Acton", html="East<br/>Acton", variableName="East_Acton")
    add_station(name="White City", html="White<br/>City", variableName="White_City")
    add_station(name="Shepherd's Bush", html="Shepherd's<br/>Bush", variableName="Shepherds_Bush")
    add_station(name="Holland Park", html="Holland<br/>Park", variableName="Holland_Park")
    add_station(name="Notting Hill Gate", html="Notting<br/>Hill Gate", variableName="Notting_Hill_Gate")
    add_station(name="Queensway", html="Queensway", variableName="Queensway")
    add_station(name="Lancaster Gate", html="Lancaster<br/>Gate", variableName="Lancaster_Gate")
    add_station(name="Marble Arch", html="Marble<br/>Arch", variableName="Marble_Arch")
    add_station(name="Bond Street", html="Bond<br/>Street", variableName="Bond_Street")
    add_station(name="Oxford Circus", html="Oxford<br />Circus", variableName="Oxford_Circus")
    add_station(name="Tottenham Court Road", html="Tottenham<br />Court Road", variableName="Tottenham_Court_Road")
    add_station(name="Holborn", html="Holborn", variableName="Holborn")
    add_station(name="Chancery Lane", html="Chancery<br/>Lane", variableName="Chancery_Lane")
    add_station(name="St. Paul's", html="St. Paul's", variableName="St_Pauls")
    add_station(name="Bank", html="<br/>Bank", variableName="Bank")
    add_station(name="Bethnal Green", html="Bethnal<br/>Green", variableName="Bethnal_Green")
    add_station(name="Mile End", html="<br/>Mile End", variableName="Mile_End")
    add_station(name="Stratford", html="Stratford", variableName="Stratford")
    add_station(name="Leyton", html="Leyton", variableName="Leyton")
    add_station(name="Leytonstone", html="Leytonstone", variableName="Leytonstone")
    add_station(name="Snaresbrook", html="Snaresbrook", variableName="Snaresbrook")
    add_station(name="South Woodford", html="South Woodford", variableName="South_Woodford")
    add_station(name="Woodford", html="Woodford", variableName="Woodford")
    add_station(name="Buckhurst Hill", html="Buckhurst Hill", variableName="Buckhurst_Hill")
    add_station(name="Loughton", html="Loughton", variableName="Loughton")
    add_station(name="Debden", html="Debden", variableName="Debden")
    add_station(name="Theydon Bois", html="Theydon Bois", variableName="Theydon_Bois")
    add_station(name="Epping", html="Epping", variableName="Epping")
    add_station(name="Roding Valley", html="Roding<br/>Valley", variableName="Roding_Valley")
    add_station(name="Chigwell", html="Chigwell", variableName="Chigwell")
    add_station(name="Grange Hill", html="Grange<br/>Hill", variableName="Grange_Hill")
    add_station(name="Hainault", html="Hainault", variableName="Hainault")
    add_station(name="Fairlop", html="Fairlop", variableName="Fairlop")
    add_station(name="Barkingside", html="Barkingside", variableName="Barkingside")
    add_station(name="Newbury Park", html="Newbury Park", variableName="Newbury_Park")
    add_station(name="Gants Hill", html="Gants<br/>Hill", variableName="Gants_Hill")
    add_station(name="Redbridge", html="Redbridge", variableName="Redbridge")
    add_station(name="Wanstead", html="Wanstead", variableName="Wanstead")
    add_station(name="Uxbridge", html="Uxbridge", variableName="Uxbridge")
    add_station(name="Hillingdon", html="<br/>Hillingdon", variableName="Hillingdon")
    add_station(name="Ickenham", html="Ickenham", variableName="Ickenham")
    add_station(name="Ruislip", html="<br/>Ruislip", variableName="Ruislip")
    add_station(name="Ruislip Manor", html="Ruislip Manor", variableName="Ruislip_Manor")
    add_station(name="Eastcote", html="Eastcote", variableName="Eastcote")
    add_station(name="Rayners Lane", html="Rayners Lane", variableName="Rayners_Lane")
    add_station(name="South Harrow", html="South Harrow", variableName="South_Harrow")
    add_station(name="Sudbury Hill", html="Sudbury Hill", variableName="Sudbury_Hill")
    add_station(name="Sudbury Town", html="Sudbury Town", variableName="Sudbury_Town")
    add_station(name="Alperton", html="Alperton", variableName="Alperton")
    add_station(name="Park Royal", html="Park Royal", variableName="Park_Royal")
    add_station(name="North Ealing", html="North Ealing", variableName="North_Ealing")
    add_station(name="Ealing Common", html="Ealing Common", variableName="Ealing_Common")
    add_station(name="Acton Town", html="Acton Town", variableName="Acton_Town")
    add_station(name="South Ealing", html="South Ealing", variableName="South_Ealing")
    add_station(name="Northfields", html="Northfields", variableName="Northfields")
    add_station(name="Boston Manor", html="Boston Manor", variableName="Boston_Manor")
    add_station(name="Osterley", html="Osterley", variableName="Osterley")
    add_station(name="Hounslow East", html="<br/>Hounslow East", variableName="Hounslow_East")
    add_station(name="Hounslow Central", html="Hounslow Central", variableName="Hounslow_Central")
    add_station(name="Hounslow West", html="Hounslow<br/>West", variableName="Hounslow_West")
    add_station(name="Hatton Cross", html="Hatton Cross", variableName="Hatton_Cross")
    add_station(name="Heathrow Terminals 1, 2, 3", html="Heathrow<br/>Terminals 1, 2, 3", variableName="Heathrow_Terminals_1_2_3")
    add_station(name="Heathrow Terminal 4", html="Heathrow<br/>Terminal 4", variableName="Heathrow_Terminal_4")
    add_station(name="Heathrow Terminal 5", html="<br/>Heathrow Terminal 5", variableName="Heathrow_Terminal_5")
    add_station(name="Hammersmith", html="Hammersmith", variableName="Hammersmith")
    add_station(name="Barons Court", html="Barons<br/>Court", variableName="Barons_Court")
    add_station(name="Earl's Court", html="Earl's<br/>Court", variableName="Earls_Court")
    add_station(name="Gloucester Road", html="Gloucester<br/>Road", variableName="Gloucester_Road")
    add_station(name="South Kensington", html="South<br/>Kensington", variableName="South_Kensington")
    add_station(name="Knightsbridge", html="Knightsbridge", variableName="Knightsbridge")
    add_station(name="Hyde Park Corner", html="Hyde Park Corner", variableName="Hyde_Park_Corner")
    add_station(name="Green Park", html="<br/>Green Park", variableName="Green_Park")
    add_station(name="Piccadilly Circus", html="Piccadilly<br/>Circus", variableName="Piccadilly_Circus")
    add_station(name="Leicester Square", html="<br/>Leicester Square", variableName="Leicester_Square")
    add_station(name="Covent Garden", html="<br/>Covent Garden", variableName="Covent_Garden")
    add_station(name="Russell Square", html="Russell<br/>Square", variableName="Russell_Square")
    add_station(name="King's Cross St. Pancras", html="King's Cross<br/>St. Pancras", variableName="Kings_Cross_St_Pancras")
    add_station(name="Caledonian Road", html="Caledonian Road", variableName="Caledonian_Road")
    add_station(name="Holloway Road", html="Holloway Road", variableName="Holloway_Road")
    add_station(name="Arsenal", html="Arsenal", variableName="Arsenal")
    add_station(name="Finsbury Park", html="Finsbury Park", variableName="Finsbury_Park")
    add_station(name="Manor House", html="Manor House", variableName="Manor_House")
    add_station(name="Turnpike Lane", html="Turnpike Lane", variableName="Turnpike_Lane")
    add_station(name="Wood Green", html="Wood Green", variableName="Wood_Green")
    add_station(name="Bounds Green", html="Bounds Green", variableName="Bounds_Green")
    add_station(name="Arnos Grove", html="Arnos Grove", variableName="Arnos_Grove")
    add_station(name="Southgate", html="Southgate", variableName="Southgate")
    add_station(name="Oakwood", html="Oakwood", variableName="Oakwood")
    add_station(name="Cockfosters", html="Cockfosters", variableName="Cockfosters")
    add_station(name="Amersham", html="Amersham", variableName="Amersham")
    add_station(name="Chesham", html="<br/>Chesham", variableName="Chesham")
    add_station(name="Chalfont & Latimer", html="Chalfont &amp;<br/>Latimer", variableName="Chalfont__Latimer")
    add_station(name="Chorleywood", html="Chorleywood", variableName="Chorleywood")
    add_station(name="Rickmansworth", html="<br/>Rickmansworth", variableName="Rickmansworth")
    add_station(name="Watford", html="Watford", variableName="Watford")
    add_station(name="Croxley", html="Croxley", variableName="Croxley")
    add_station(name="Moor Park", html="Moor Park", variableName="Moor_Park")
    add_station(name="Northwood", html="Northwood", variableName="Northwood")
    add_station(name="Northwood Hills", html="Northwood<br/>Hills", variableName="Northwood_Hills")
    add_station(name="Pinner", html="Pinner", variableName="Pinner")
    add_station(name="North Harrow", html="North Harrow", variableName="North_Harrow")
    add_station(name="West Harrow", html="West<br/>Harrow", variableName="West_Harrow")
    add_station(name="Harrow-on-the-Hill", html="Harrow-<br/>on-the-Hill", variableName="Harrow_on_the_Hill")
    add_station(name="Northwick Park", html="Northwick<br/>Park", variableName="Northwick_Park")
    add_station(name="Preston Road", html="Preston<br/>Road", variableName="Preston_Road")
    add_station(name="Wembley Park", html="Wembley<br/>Park", variableName="Wembley_Park")
    add_station(name="Finchley Road", html="Finchley Road", variableName="Finchley_Road")
    add_station(name="Baker Street", html="Baker<br/>Street", variableName="Baker_Street")
    add_station(name="Euston Square", html="Euston<br/>Square", variableName="Euston_Square")
    add_station(name="Barbican", html="<br/>Barbican", variableName="Barbican")
    add_station(name="Aldgate", html="Aldgate", variableName="Aldgate")
    add_station(name="Chiswick Park", html="Chiswick<br/>Park", variableName="Chiswick_Park")
    add_station(name="Turnham Green", html="Turnham<br/>Green", variableName="Turnham_Green")
    add_station(name="Stamford Brook", html="Stamford<br/>Brook", variableName="Stamford_Brook")
    add_station(name="West Kensington", html="West<br/>Kensington", variableName="West_Kensington")
    add_station(name="Fulham Broadway", html="Fulham Broadway", variableName="Fulham_Broadway")
    add_station(name="Parsons Green", html="Parsons Green", variableName="Parsons_Green")
    add_station(name="Putney Bridge", html="Putney Bridge", variableName="Putney_Bridge")
    add_station(name="East Putney", html="East Putney", variableName="East_Putney")
    add_station(name="Southfields", html="Southfields", variableName="Southfields")
    add_station(name="Wimbledon Park", html="Wimbledon Park", variableName="Wimbledon_Park")
    add_station(name="Wimbledon", html="Wimbledon", variableName="Wimbledon")
    add_station(name="Edgware Road", html="Edgware Road", variableName="Edgware_Road")
    add_station(name="Bayswater", html="Bayswater", variableName="Bayswater")
    add_station(name="High Street Kensington", html="High Street<br/>Kensington", variableName="High_Street_Kensington")
    add_station(name="Sloane Square", html="Sloane<br/>Square", variableName="Sloane_Square")
    add_station(name="Victoria", html="Victoria", variableName="Victoria")
    add_station(name="St.James's Park", html="St.James's<br/>Park", variableName="StJamess_Park")
    add_station(name="Westminster", html="Westminster", variableName="Westminster")
    add_station(name="Temple", html="Temple", variableName="Temple")
    add_station(name="Blackfriars", html="<br/>Blackfriars", variableName="Blackfriars")
    add_station(name="Mansion House", html="Mansion House", variableName="Mansion_House")
    add_station(name="Cannon Street", html="<br/>Cannon Street", variableName="Cannon_Street")
    add_station(name="Tower Hill", html="Tower<br/>Hill", variableName="Tower_Hill")
    add_station(name="Aldgate East", html="Aldgate<br/>East", variableName="Aldgate_East")
    add_station(name="Whitechapel", html="<br/>Whitechapel", variableName="Whitechapel")
    add_station(name="Stepney Green", html="<br/>Stepney Green", variableName="Stepney_Green")
    add_station(name="Bow Road", html="Bow Road", variableName="Bow_Road")
    add_station(name="Bromley-by-Bow", html="Bromley-<br/>by-Bow", variableName="Bromley_by_Bow")
    add_station(name="Plaistow", html="<br/>Plaistow", variableName="Plaistow")
    add_station(name="Upton Park", html="<br/>Upton Park", variableName="Upton_Park")
    add_station(name="East Ham", html="East Ham", variableName="East_Ham")
    add_station(name="Barking", html="<br/>Barking", variableName="Barking")
    add_station(name="Upney", html="<br/>Upney", variableName="Upney")
    add_station(name="Becontree", html="Becontree", variableName="Becontree")
    add_station(name="Dagenham Heathway", html="Dagenham<br/>Heathway", variableName="Dagenham_Heathway")
    add_station(name="Dagenham East", html="Dagenham<br/>East", variableName="Dagenham_East")
    add_station(name="Elm Park", html="<br/>Elm Park", variableName="Elm_Park")
    add_station(name="Hornchurch", html="<br/>Hornchurch", variableName="Hornchurch")
    add_station(name="Upminster Bridge", html="Upminster Bridge", variableName="Upminster_Bridge")
    add_station(name="Upminster", html="<br/>Upminster", variableName="Upminster")
    add_station(name="Ravenscourt Park", html="Ravenscourt<br/>Park", variableName="Ravenscourt_Park")
    add_station(name="Gunnersbury", html="Gunnersbury", variableName="Gunnersbury")
    add_station(name="Kew Gardens", html="Kew Gardens", variableName="Kew_Gardens")
    add_station(name="Richmond", html="Richmond", variableName="Richmond")
    add_station(name="Monument", html="Monument", variableName="Monument")
    add_station(name="Kensington (Olympia)", html="Kensington<br/>(Olympia)", variableName="Kensington_Olympia")
    add_station(name="Liverpool Street", html="Liverpool<br/>Street", variableName="Liverpool_Street")
    add_station(name="Moorgate", html="<br/>Moorgate", variableName="Moorgate")
    add_station(name="Farringdon", html="<br/>Farringdon", variableName="Farringdon")
    add_station(name="Ladbroke Grove", html="<br/>Ladbroke Grove", variableName="Ladbroke_Grove")
    add_station(name="Latimer Road", html="<br/>Latimer Road", variableName="Latimer_Road")
    add_station(name="Wood Lane", html="<br/>Wood Lane", variableName="Wood_Lane")
    add_station(name="Goldhawk Road", html="Goldhawk Road", variableName="Goldhawk_Road")
    add_station(name="Shepherd's Bush Market", html="Shepherd's Bush<br/>Market", variableName="Shepherds_Bush_Market")
    add_station(name="Westbourne Park", html="Westbourne Park", variableName="Westbourne_Park")
    add_station(name="Royal Oak", html="Royal Oak", variableName="Royal_Oak")
    add_station(name="Great Portland Street", html="Great Portland Street", variableName="Great_Portland_Street")
    add_station(name="Harrow & Wealdstone", html="Harrow &amp;<br/>Wealdstone", variableName="Harrow__Wealdstone")
    add_station(name="South Kenton", html="South Kenton", variableName="South_Kenton")
    add_station(name="North Wembley", html="North Wembley", variableName="North_Wembley")
    add_station(name="Wembley Central", html="Wembley Central", variableName="Wembley_Central")
    add_station(name="Stonebridge Park", html="Stonebridge Park", variableName="Stonebridge_Park")
    add_station(name="Harlesden", html="Harlesden", variableName="Harlesden")
    add_station(name="Willesden Junction", html="Willesden Junction", variableName="Willesden_Junction")
    add_station(name="Queen's Park", html="Queen's Park", variableName="Queens_Park")
    add_station(name="Kilburn Park", html="Kilburn Park", variableName="Kilburn_Park")
    add_station(name="Maida Vale", html="Maida Vale", variableName="Maida_Vale")
    add_station(name="Warwick Avenue", html="Warwick Avenue", variableName="Warwick_Avenue")
    add_station(name="Paddington", html="<br/>Paddington", variableName="Paddington")
    add_station(name="Marylebone", html="<br/>Marylebone", variableName="Marylebone")
    add_station(name="Regent's Park", html="Regent's Park", variableName="Regents_Park")
    add_station(name="Charing Cross", html="Charing<br/>Cross", variableName="Charing_Cross")
    add_station(name="Embankment", html="Embankment", variableName="Embankment")
    add_station(name="Lambeth North", html="Lambeth<br/>North", variableName="Lambeth_North")
    add_station(name="Elephant & Castle", html="Elephant &amp; Castle", variableName="Elephant__Castle")
    add_station(name="Walthamstow Central", html="Walthamstow<br/>Central", variableName="Walthamstow_Central")
    add_station(name="Blackhorse Road", html="Blackhorse<br/>Road", variableName="Blackhorse_Road")
    add_station(name="Tottenham Hale", html="Tottenham<br/>Hale", variableName="Tottenham_Hale")
    add_station(name="Seven Sisters", html="Seven<br/>Sisters", variableName="Seven_Sisters")
    add_station(name="Highbury & Islington", html="Highbury &amp;<br/>Islington", variableName="Highbury__Islington")
    add_station(name="Warren Street", html="Warren Street", variableName="Warren_Street")
    add_station(name="Pimlico", html="Pimlico", variableName="Pimlico")
    add_station(name="Vauxhall", html="Vauxhall", variableName="Vauxhall")
    add_station(name="Stockwell", html="Stockwell", variableName="Stockwell")
    add_station(name="Brixton", html="<br/>Brixton", variableName="Brixton")
    add_station(name="High Barnet", html="High Barnet", variableName="High_Barnet")
    add_station(name="Totteridge & Whetstone", html="Totteridge &amp; Whetstone", variableName="Totteridge__Whetstone")
    add_station(name="Woodside Park", html="Woodside Park", variableName="Woodside_Park")
    add_station(name="West Finchley", html="West Finchley", variableName="West_Finchley")
    add_station(name="Mill Hill East", html="Mill Hill East", variableName="Mill_Hill_East")
    add_station(name="Finchley Central", html="Finchley Central", variableName="Finchley_Central")
    add_station(name="East Finchley", html="East Finchley", variableName="East_Finchley")
    add_station(name="Highgate", html="Highgate", variableName="Highgate")
    add_station(name="Archway", html="Archway", variableName="Archway")
    add_station(name="Tufnell Park", html="Tufnell Park", variableName="Tufnell_Park")
    add_station(name="Kentish Town", html="Kentish Town", variableName="Kentish_Town")
    add_station(name="Edgware", html="Edgware", variableName="Edgware")
    add_station(name="Burnt Oak", html="Burnt Oak", variableName="Burnt_Oak")
    add_station(name="Colindale", html="Colindale", variableName="Colindale")
    add_station(name="Hendon Central", html="Hendon Central", variableName="Hendon_Central")
    add_station(name="Brent Cross", html="Brent Cross", variableName="Brent_Cross")
    add_station(name="Golders Green", html="Golders Green", variableName="Golders_Green")
    add_station(name="Hampstead", html="Hampstead", variableName="Hampstead")
    add_station(name="Belsize Park", html="Belsize Park", variableName="Belsize_Park")
    add_station(name="Chalk Farm", html="Chalk Farm", variableName="Chalk_Farm")
    add_station(name="Camden Town", html="Camden Town", variableName="Camden_Town")
    add_station(name="Mornington Crescent", html="Mornington<br/>Crescent", variableName="Mornington_Crescent")
    add_station(name="Goodge Street", html="Goodge<br/>Street", variableName="Goodge_Street")
    add_station(name="Angel", html="Angel", variableName="Angel")
    add_station(name="Old Street", html="Old Street", variableName="Old_Street")
    add_station(name="London Bridge", html="<br/>London<br/>Bridge", variableName="London_Bridge")
    add_station(name="Borough", html="<br/>Borough", variableName="Borough")
    add_station(name="Kennington", html="<br/>Kennington", variableName="Kennington")
    add_station(name="Oval", html="Oval", variableName="Oval")
    add_station(name="Clapham North", html="Clapham North", variableName="Clapham_North")
    add_station(name="Clapham Common", html="Clapham Common", variableName="Clapham_Common")
    add_station(name="Clapham South", html="Clapham South", variableName="Clapham_South")
    add_station(name="Balham", html="<br/>Balham", variableName="Balham")
    add_station(name="Tooting Bec", html="Tooting Bec", variableName="Tooting_Bec")
    add_station(name="Tooting Broadway", html="Tooting Broadway", variableName="Tooting_Broadway")
    add_station(name="Colliers Wood", html="Colliers Wood", variableName="Colliers_Wood")
    add_station(name="South Wimbledon", html="South Wimbledon", variableName="South_Wimbledon")
    add_station(name="Morden", html="<br>Morden", variableName="Morden")
    add_station(name="Stanmore", html="Stanmore", variableName="Stanmore")
    add_station(name="Canons Park", html="Canons Park", variableName="Canons_Park")
    add_station(name="Queensbury", html="Queensbury", variableName="Queensbury")
    add_station(name="Kingsbury", html="Kingsbury", variableName="Kingsbury")
    add_station(name="Neasden", html="Neasden", variableName="Neasden")
    add_station(name="Dollis Hill", html="Dollis Hill", variableName="Dollis_Hill")
    add_station(name="Willesden Green", html="Willesden Green", variableName="Willesden_Green")
    add_station(name="Kilburn", html="Kilburn", variableName="Kilburn")
    add_station(name="West Hampstead", html="West Hampstead", variableName="West_Hampstead")
    add_station(name="Swiss Cottage", html="Swiss Cottage", variableName="Swiss_Cottage")
    add_station(name="St. John's Wood", html="St. John's Wood", variableName="St_Johns_Wood")
    add_station(name="Waterloo", html="Waterloo", variableName="Waterloo")
    add_station(name="Southwark", html="Southwark", variableName="Southwark")
    add_station(name="Bermondsey", html="Bermondsey", variableName="Bermondsey")
    add_station(name="Canada Water", html="Canada Water", variableName="Canada_Water")
    add_station(name="Canary Wharf", html="<br/>Canary Wharf", variableName="Canary_Wharf")
    add_station(name="North Greenwich", html="North<br/>Greenwich", variableName="North_Greenwich")
    add_station(name="Watford Junction", html="Watford Junction", variableName="Watford_Junction")
    add_station(name="Watford High Street", html="Watford High Street", variableName="Watford_High_Street")
    add_station(name="Bushey", html="Bushey", variableName="Bushey")
    add_station(name="Carpenders Park", html="Carpenders Park", variableName="Carpenders_Park")
    add_station(name="Hatch End", html="Hatch End", variableName="Hatch_End")
    add_station(name="Headstone Lane", html="Headstone Lane", variableName="Headstone_Lane")
    add_station(name="Kenton", html="Kenton", variableName="Kenton")
    add_station(name="Kensal Green", html="Kensal Green", variableName="Kensal_Green")
    add_station(name="Kilburn High Road", html="Kilburn<br/>High Road", variableName="Kilburn_High_Road")
    add_station(name="South Hampstead", html="South<br/>Hampstead", variableName="South_Hampstead")
    add_station(name="Euston", html="Euston", variableName="Euston")
    add_station(name="Acton Central", html="Acton Central", variableName="Acton_Central")
    add_station(name="South Acton", html="South Acton", variableName="South_Acton")
    add_station(name="West Brompton", html="West Brompton", variableName="West_Brompton")
    add_station(name="Imperial Wharf", html="Imperial<br/>Wharf", variableName="Imperial_Wharf")
    add_station(name="Clapham Junction", html="Clapham<br/>Junction", variableName="Clapham_Junction")
    add_station(name="Wandsworth Road", html="Wandsworth<br/>Road", variableName="Wandsworth_Road")
    add_station(name="Clapham High Street", html="Clapham High Street", variableName="Clapham_High_Street")
    add_station(name="Denmark Hill", html="<br/>Denmark Hill", variableName="Denmark_Hill")
    add_station(name="Peckham Rye", html="<br/>Peckham Rye", variableName="Peckham_Rye")
    add_station(name="Queens Road Peckham", html="Queens Road<br/>Peckham", variableName="Queens_Road_Peckham")
    add_station(name="New Cross Gate", html="New Cross<br/>Gate", variableName="New_Cross_Gate")
    add_station(name="Brockley", html="Brockley", variableName="Brockley")
    add_station(name="Honor Oak Park", html="Honor Oak Park", variableName="Honor_Oak_Park")
    add_station(name="Forest Hill", html="Forest Hill", variableName="Forest_Hill")
    add_station(name="Sydenham", html="Sydenham", variableName="Sydenham")
    add_station(name="Penge West", html="Penge West", variableName="Penge_West")
    add_station(name="Anerley", html="Anerley", variableName="Anerley")
    add_station(name="Norwood Junction", html="Norwood Junction", variableName="Norwood_Junction")
    add_station(name="West Croydon", html="West Croydon", variableName="West_Croydon")
    add_station(name="Crystal Palace", html="Crystal Palace", variableName="Crystal_Palace")
    add_station(name="New Cross", html="New Cross", variableName="New_Cross")
    add_station(name="Surrey Quays", html="Surrey Quays", variableName="Surrey_Quays")
    add_station(name="Rotherhithe", html="Rotherhithe", variableName="Rotherhithe")
    add_station(name="Wapping", html="Wapping", variableName="Wapping")
    add_station(name="Shadwell", html="Shadwell", variableName="Shadwell")
    add_station(name="Shoreditch High Street", html="Shoreditch<br/>High Street", variableName="Shoreditch_High_Street")
    add_station(name="Hoxton", html="Hoxton", variableName="Hoxton")
    add_station(name="Haggerston", html="Haggerston", variableName="Haggerston")
    add_station(name="Dalston Junction", html="Dalston Junction", variableName="Dalston_Junction")
    add_station(name="Canonbury", html="Canonbury", variableName="Canonbury")
    add_station(name="Hackney Wick", html="Hackney<br/>Wick", variableName="Hackney_Wick")
    add_station(name="Homerton", html="Homerton", variableName="Homerton")
    add_station(name="Hackney Central", html="Hackney<br/>Central", variableName="Hackney_Central")
    add_station(name="Dalston Kingsland", html="Dalston<br/>Kingsland", variableName="Dalston_Kingsland")
    add_station(name="Caledonian Road & Barnsbury", html="Caledonian<br/>Road &amp;</br>Barnsbury", variableName="Caledonian_Road__Barnsbury")
    add_station(name="Camden Road", html="Camden</br>Road", variableName="Camden_Road")
    add_station(name="Kentish Town West", html="Kentish<br/>Town West", variableName="Kentish_Town_West")
    add_station(name="Hampstead Heath", html="Hampstead<br/>Heath", variableName="Hampstead_Heath")
    add_station(name="Finchley Road & Frognal", html="Finchley Road<br/>&amp; Frognal", variableName="Finchley_Road__Frognal")
    add_station(name="Brondesbury", html="Brondesbury", variableName="Brondesbury")
    add_station(name="Brondesbury Park", html="Brondesbury<br/>Park", variableName="Brondesbury_Park")
    add_station(name="Kensal Rise", html="Kensal<br/>Rise", variableName="Kensal_Rise")
    add_station(name="Gospel Oak", html="Gospel<br/>Oak", variableName="Gospel_Oak")
    add_station(name="Upper Holloway", html="<br/>Upper Holloway", variableName="Upper_Holloway")
    add_station(name="Crouch Hill", html="<br/>Crouch Hill", variableName="Crouch_Hill")
    add_station(name="Harringay Green Lanes", html="Harringay<br/>Green Lanes", variableName="Harringay_Green_Lanes")
    add_station(name="South Tottenham", html="South Tottenham", variableName="South_Tottenham")
    add_station(name="Walthamstow Queens Road", html="Walthamstow<br/>Queens Road", variableName="Walthamstow_Queens_Road")
    add_station(name="Leyton Midland Road", html="Leyton<br/>Midland Road", variableName="Leyton_Midland_Road")
    add_station(name="Leytonstone High Road", html="Leytonstone<br/>High Road", variableName="Leytonstone_High_Road")
    add_station(name="Wanstead Park", html="Wanstead Park", variableName="Wanstead_Park")
    add_station(name="Woodgrange Park", html="Woodgrange Park", variableName="Woodgrange_Park")
    add_station(name="Limehouse", html="Limehouse", variableName="Limehouse")
    add_station(name="Westferry", html="<br/>Westferry", variableName="Westferry")
    add_station(name="Poplar", html="<br/>Poplar", variableName="Poplar")
    add_station(name="Blackwall", html="<br/>Blackwall", variableName="Blackwall")
    add_station(name="East India", html="East<br/>India", variableName="East_India")
    add_station(name="Royal Victoria", html="Royal Victoria", variableName="Royal_Victoria")
    add_station(name="Custom House for ExCel", html="Custom House for ExCel", variableName="Custom_House_for_ExCel")
    add_station(name="Prince Regent", html="Prince Regent", variableName="Prince_Regent")
    add_station(name="Royal Albert", html="Royal Albert", variableName="Royal_Albert")
    add_station(name="Beckton Park", html="Beckton Park", variableName="Beckton_Park")
    add_station(name="Cyprus", html="Cyprus", variableName="Cyprus")
    add_station(name="Gallions Reach", html="Gallions<br/>Reach", variableName="Gallions_Reach")
    add_station(name="Beckton", html="Beckton", variableName="Beckton")
    add_station(name="West Silvertown", html="West<br/>Silvertown", variableName="West_Silvertown")
    add_station(name="Pontoon Dock", html="Pontoon Dock", variableName="Pontoon_Dock")
    add_station(name="London City Airport", html="London<br/>City Airport", variableName="London_City_Airport")
    add_station(name="King George V", html="King George V", variableName="King_George_V")
    add_station(name="Woolwich Arsenal", html="Woolwich<br/>Arsenal", variableName="Woolwich_Arsenal")
    add_station(name="Canning Town", html="Canning<br/>Town", variableName="Canning_Town")
    add_station(name="Star Lane", html="Star Lane", variableName="Star_Lane")
    add_station(name="West Ham", html="West Ham", variableName="West_Ham")
    add_station(name="Abbey Road", html="Abbey<br/>Road", variableName="Abbey_Road")
    add_station(name="Stratford High Street", html="Stratford<br/>High Street", variableName="Stratford_High_Street")
    add_station(name="Stratford International", html="Stratford<br/>International", variableName="Stratford_International")
    add_station(name="Pudding Mill Lane", html="Pudding<br/>Mill Lane", variableName="Pudding_Mill_Lane")
    add_station(name="Bow Church", html="Bow Church", variableName="Bow_Church")
    add_station(name="Devons Road", html="Devons Road", variableName="Devons_Road")
    add_station(name="Langdon Park", html="Langdon Park", variableName="Langdon_Park")
    add_station(name="All Saints", html="All Saints", variableName="All_Saints")
    add_station(name="West India Quay", html="West<br/>India Quay", variableName="West_India_Quay")
    add_station(name="Heron Quays", html="Heron Quays", variableName="Heron_Quays")
    add_station(name="South Quay", html="South Quay", variableName="South_Quay")
    add_station(name="Crossharbour", html="Crossharbour", variableName="Crossharbour")
    add_station(name="Mudchute", html="Mudchute", variableName="Mudchute")
    add_station(name="Island Gardens", html="Island Gardens", variableName="Island_Gardens")
    add_station(name="Cutty Sark for Maritime Greenwich", html="Cutty Sark for<br/>Maritime Greenwich", variableName="Cutty_Sark_for_Maritime_Greenwich")
    add_station(name="Greenwich", html="Greenwich", variableName="Greenwich")
    add_station(name="Deptford Bridge", html="Deptford Bridge", variableName="Deptford_Bridge")
    add_station(name="Elverson Road", html="Elverson Road", variableName="Elverson_Road")
    add_station(name="Lewisham", html="Lewisham", variableName="Lewisham")
    add_station(name="Tower Gateway", html="<br/>Tower<br/>Gateway", variableName="Tower_Gateway")
    add_station(name="Emirates Royal Docks", html="Emirates<br/>Royal Docks", variableName="Emirates_Royal_Docks")
    add_station(name="Emirates Greenwich Peninsula", html="Emirates<br/>Greenwich<br/>Peninsula", variableName="Emirates_Greenwich_Peninsula")


    for i in range(0, settings.NUMBER_OF_CLUSTERING_ALGORITHMS):
        ClusterRecord.objects.get_or_create(clusterType=i, timesUsed=0, timesChanged=0)[0]


    # Print out what we have added to the user.
    for c in TubeStations.objects.all():
        print "- {0}".format(str(c))

def add_station(name, html, variableName):
    p = TubeStations.objects.get_or_create(stationName=name, stationNameHTML=html, stationNameVariable=variableName)[0]
    return p



# Start execution here!
if __name__ == '__main__':
    print "Starting Tube Station population script..."
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'friend_tube_map_project.settings')
    from django.conf import settings
    from tubemap.models import TubeStations
    from frontpage.models import ClusterRecord
    populate()